name: CI
on: [push]
jobs:
  jenkins:
    runs-on: ubuntu-latest
    container:
       image: ghcr.io/jenkinsci/jenkinsfile-runner:master
    steps:
        - uses: actions/checkout@v2
        - name: Jenkins pipeline 
          id: jenkins_pipeline
          uses:
            jenkinsci/jfr-container-action@master
          with:
            command: run
            jenkinsfile: Jenkinsfile
            pluginstxt: plugins.txt
