name: CI
on: [push]
jobs:
  jenkins:
    runs-on: ubuntu-latest
    container:
       image: ghcr.io/cr1t-gym/jenkinsfile-runner-image-release-test:master
    steps:
        - uses: actions/checkout@v2
        - name: Jenkins pipeline 
          id: jenkins_pipeline
          uses:
            Cr1t-GYM/jenkins-action-poc/jfr-container-action@master
          with:
            command: run
            jenkinsfile: Jenkinsfile
            pluginstxt: plugins.txt
