on: push
name: Jenkins
jobs:
  jenkinsfile-runner:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:master
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: jenkinsci/jfr-setup-action@master
    - uses: jenkinsci/jfr-runtime-action@master
      with:
        command: run
        jenkinsfile: Jenkinsfile
