on: push
name: Jenkins
jobs:
  jenkinsfile-runner:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jenkinsci/jenkinsfile-runner:master
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    # - uses: jenkinsci/jfr-setup-action@master
    # - uses: jenkinsci/jfr-runtime-action@master
    #   with:
    #     command: run
    #     jenkinsfile: Jenkinsfile
    - uses:
        jenkinsci/jfr-static-image-action@master
      with:
        command: run
        jenkinsfile: Jenkinsfile
